"""empty message

Revision ID: 321da92ea509
Revises: 71448e8ae77f
Create Date: 2018-04-11 16:40:09.092093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321da92ea509'
down_revision = '71448e8ae77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('establishments')
    # ### end Alembic commands ###
