"""empty message

Revision ID: 71448e8ae77f
Revises: 7e688a55b96b
Create Date: 2018-04-10 15:31:40.417349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71448e8ae77f'
down_revision = '7e688a55b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_type')
    # ### end Alembic commands ###
